name=HoltzLib
version=1.0.1
author=Kyle Holtz
maintainer=Kyle Holtz
sentence=Simple abstractions for motors and sensors.
paragraph=Utility classes, including DCMotor and UltrasonicSensor.
category=Device Control
url=https://github.com/KE-Holtz/holtzlib
architectures=*
