name=HoltzLib
version=1.0.0
author=Kyle Holtz
maintainer=Kyle Holtz
sentence=Simple abstractions for motors and sensors.
paragraph=DCMotor and UltrasonicSensor utility classes. WIP
category=Device Control
url=https://github.com/KE-Holtz/holtzlib
architectures=*
